apiVersion: apps/v1
kind: Deployment
metadata:
  name: pape-siriman-cissoko
  labels:
    app: pape-siriman-cissoko
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pape-siriman-cissoko
  template:
    metadata:
      labels:
        app: pape-siriman-cissoko
    spec:
      containers:
        - name: pape-siriman-cissoko
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}