replicaCount: 2

image:
  repository: papesiriman/pape-siriman-cissoko-app
  tag: cf05c482376fe2042c5f887e746cf7419c6c039c
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"